sudo: required
service: docker
 
before_install:
  - docker pull nimlang/nim:1.2.4-alpine-regular
script:
  - docker run nimlang/nim nim --version
  - docker run -v "$(pwd):/project" -w /project --rm nimlang/nim:1.2.4-alpine-regular sh -c "apk add --no-cache zip zlib-dev && nimble install -y zip docopt terminaltables && sh src/build.sh &&  sh test/all.sh"
 