sudo: required
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libzip-dev
  - docker pull nimlang/nim
script:
  - docker run nimlang/nim nim --version
  - docker run -v "$(pwd):/project" -w /project nimlang/nim sh -c "nimble refresh && nimble qax &&  bash test/all.sh "
