# copied from Daniel Cook's Seq collection
name: "Build"

on: 
  - push
  - pull_request

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        nimversion:
        - stable
        - devel


    steps:
    - uses: actions/checkout@v2

    # Caching
    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-stable

    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-stable
 
    # Install Dependencies
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get -qy install  make build-essential cmake libncurses-dev ncurses-dev libbz2-dev lzma-dev liblzma-dev \
             curl libssl-dev libtool autoconf automake libcurl4-openssl-dev zlib1g-dev


    - uses: iffy/install-nim@v3.2.0
      with:
        version: ${{ matrix.nimversion }}

    # Build and Test
    - name: Build macOS executable
      if: runner.os == 'macOS'
      run: |
        nimble build -y --verbose 
        ls -l bin/
        
        bin/qax --version
        bash test/all.sh
        
        
        
    - name: Build and Test Linux executable
      if: runner.os == 'Linux'
      run: |
        nimble build -y --verbose
        ls -l bin/
          
        bin/qax --version
        bash test/all.sh     
