# copied from Daniel Cook's Seq collection
name: "Build-Linux"

on: 
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04] #ubuntu-24.04
        nimversion:
        - 1.6.6


    steps:
    - uses: actions/checkout@v2

    # Caching
    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-stable

    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-stable
 
    # Install Dependencies
    - name: Install dependencies (Linux)
      run: |
        sudo apt-get update
        sudo apt-get -qy install  make build-essential cmake libncurses-dev ncurses-dev libbz2-dev lzma-dev liblzma-dev \
             curl libssl-dev libtool autoconf automake libcurl4-openssl-dev zlib1g-dev


    - uses: iffy/install-nim@v3.2.0
      with:
        version: ${{ matrix.nimversion }}
 
    - name: Build and Test Linux executable
      run: |
        nimble build -y --verbose
        ls -l bin/
        bin/qax --version
        bash test/all.sh
        mv bin/qax bin/qax-linux
    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: qax-linux
        path: /home/runner/work/qax/qax/bin/qax-linux
